[package]
name = "pridevault"
version = "0.1.0"
edition = "2021"
publish = false
authors = ["luxaway"]
license = "GPL-3.0-only"

[lib]
path = "src/lib.rs"

[dependencies]
multiversx-sc = "=0.66.2"

[dev-dependencies]
multiversx-sc-scenario = "=0.66.2"

[workspace]
members = [
    ".",
    "meta",
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = false
